# arctica-greeter
# Autogenerated from man page /usr/share/man/man1/arctica-greeter.1.gz
complete -c arctica-greeter -s v -l version --description 'Show release version.'
complete -c arctica-greeter -l test-mode --description 'Run the greeter in a test mode inside the current X session.'
complete -c arctica-greeter -s '?' -l help --description 'Show help options.  SEE ALSO lightdm.'

