# bf_tar
# Autogenerated from man page /usr/share/man/man1/bf_tar.1.gz
complete -c bf_tar -s r --description 'option causes bf_tar to remove inactive log files after the archive has been …'
complete -c bf_tar -s R --description 'option causes bf_tar to remove inactive log files before the archive is writt…'

