# bf_tar-bdb
# Autogenerated from man page /usr/share/man/man1/bf_tar-bdb.1.gz
complete -c bf_tar-bdb -s r --description 'option causes bf_tar to remove inactive log files after the archive has been …'
complete -c bf_tar-bdb -s R --description 'option causes bf_tar to remove inactive log files before the archive is writt…'

