# bogotune-bdb
# Autogenerated from man page /usr/share/man/man1/bogotune-bdb.1.gz
complete -c bogotune-bdb -s h --description 'option prints the help message and exits.'
complete -c bogotune-bdb -s v --description 'option increases the verbosity level.'
complete -c bogotune-bdb -s c --description 'filename option tells bogofilter to read the config file named.'
complete -c bogotune-bdb -s C --description 'option prevents bogotune from reading a configuration file.'
complete -c bogotune-bdb -s d --description 'dir option specifies the directory for the database.'
complete -c bogotune-bdb -s D --description 'option tells bogotune to build a wordlist in memory using the input messages.'
complete -c bogotune-bdb -s n --description 'option tells bogotune that the following argument is a file (or folder) conta…'
complete -c bogotune-bdb -s s --description 'option will be treated as though they had been preceded by.'
complete -c bogotune-bdb -s r --description 'option tells bogotune to use the following parameter as the robx value.'
complete -c bogotune-bdb -s T --description 'option tells bogotune to use the following parameter as fp target value.'
complete -c bogotune-bdb -s M --description 'option tells bogotune to convert the file to message count format.'
complete -c bogotune-bdb -o ddir --description 'option.  If none of that is available, bogofilter will use directory $HOME/.'

