# caja
# Autogenerated from man page /usr/share/man/man1/caja.1.gz
complete -c caja -l browser --description 'Open a browser window.'
complete -c caja -s c -l check --description 'Perform a quick set of self-check tests.'
complete -c caja -l display --description 'X display to use.'
complete -c caja -s g -l geometry --description 'Create the initial window with the given geometry.'
complete -c caja -s t -l tabs --description 'Open URIs in tabs.'
complete -c caja -s n -l no-default-window --description 'Only create windows for explicitly specified URIs.'
complete -c caja -l no-desktop --description 'Do not manage the desktop (ignore the preference set in the preferences dialo…'
complete -c caja -l force-desktop --description 'Manage the desktop regardless of set preferences or environment (on new start…'
complete -c caja -s q -l quit --description 'Quit Caja.'
complete -c caja -l version --description 'Print current version information and exit.'
complete -c caja -s '?' -s h -l help --description 'Print standard command line options.'

