# caja-sendto
# Autogenerated from man page /usr/share/man/man1/caja-sendto.1.gz
complete -c caja-sendto -s '?' -l help --description 'Show a help message listing all the options and their meanings.'

