# celluloid
# Autogenerated from man page /usr/share/man/man1/celluloid.1.gz
complete -c celluloid -s '?' -s h -l help --description 'Show help options.'
complete -c celluloid -l new-window --description 'Create a new window if there is already a running instance.'
complete -c celluloid -l enqueue --description 'Append the given files or URIs to the playlist if there is a running instance.'
complete -c celluloid -l mpv-options --description 'Deprecated.  Pass arbitrary options to mpv.'
complete -c celluloid -l mpv-MPVOPTION --description 'Set mpv option MPVOPTION to VALUE.'
complete -c celluloid -l vf --description '.'
complete -c celluloid -l version --description 'Print the release version and exit.'

