# deja-dup
# Autogenerated from man page /usr/share/man/man1/deja-dup.1.gz
complete -c deja-dup -s h -l help --description 'Show help options.'
complete -c deja-dup -l help-all --description 'Show all help options.'
complete -c deja-dup -l help-gtk --description 'Show GTK Options.'
complete -c deja-dup -l version --description 'Show version.'
complete -c deja-dup -l restore --description 'Restore given files.'
complete -c deja-dup -l backup --description 'Immediately start a backup SEE ALSO duplicity (1).'

