# engrampa
# Autogenerated from man page /usr/share/man/man1/engrampa.1.gz
complete -c engrampa -s a -l add-to --description 'Add files to the specified archive and quit the program.'
complete -c engrampa -s d -l add --description 'Add files asking the name of the archive and quit the program.'
complete -c engrampa -s e -l extract-to --description 'Extract archives to the specified folder and quit the program.'
complete -c engrampa -s f -l extract --description 'Extract archives asking the destination folder and quit the program.'
complete -c engrampa -s h -l extract-here --description 'Extract archives using the archive name as destination folder and quit the pr…'
complete -c engrampa -l default-dir --description 'Default folder to use for the \'--add\' and \'--extract\' commands.'
complete -c engrampa -l force --description 'Create destination folder without asking confirmation.'
complete -c engrampa -l display --description 'X display to use.'
complete -c engrampa -s '?' -l help --description 'Print standard command line options.'
complete -c engrampa -l help-all --description 'Print all command line options.'

