# eom
# Autogenerated from man page /usr/share/man/man1/eom.1.gz
complete -c eom -l display --description 'X display to use.'
complete -c eom -s f -l fullscreen --description 'Start eom in fullscreen mode.'
complete -c eom -s c -l disable-image-collection --description 'Disable image collection viewer.'
complete -c eom -s s -l slide-show --description 'Open in slideshow mode.'
complete -c eom -s n -l new-instance --description 'Start a new instance instead of reusing an existing window.'
complete -c eom -l version --description 'Output version information and exit.'
complete -c eom -s h -l help --description 'Print standard command line options.'

