# fzf-tmux
# Autogenerated from man page /usr/share/man/man1/fzf-tmux.1.gz
complete -c fzf-tmux -s p --description '.'
complete -c fzf-tmux -s w --description '.'
complete -c fzf-tmux -s h --description '.'
complete -c fzf-tmux -s x --description '.'
complete -c fzf-tmux -s y --description '.'
complete -c fzf-tmux -s u --description 'Split above (up).'
complete -c fzf-tmux -s d --description 'Split below (down).'
complete -c fzf-tmux -s l --description 'Split left.'
complete -c fzf-tmux -s r --description 'Split right.'

