# gnome-firmware
# Autogenerated from man page /usr/share/man/man1/gnome-firmware.1.gz
complete -c gnome-firmware -s h -l help --description 'Show help options.'
complete -c gnome-firmware -l help-all --description 'Show all help options.'
complete -c gnome-firmware -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c gnome-firmware -s v -l verbose --description 'Show extra debugging information.'
complete -c gnome-firmware -l display --description 'X display to use.'

