# gpick
# Autogenerated from man page /usr/share/man/man1/gpick.1.gz
complete -c gpick -s h -l help --description 'Show help options.'
complete -c gpick -l help-all --description 'Show all help options.'
complete -c gpick -l help-gtk --description 'Show GTK+ Options APPLICATION OPTIONS.'
complete -c gpick -s g -l geometry --description 'Window geometry.'
complete -c gpick -s p -l pick --description 'Pick a color.'
complete -c gpick -s v -l version --description 'Print version information.'
complete -c gpick -l display --description 'X display to use.'

