# gtk-redshift
# Autogenerated from man page /usr/share/man/man1/gtk-redshift.1.gz
complete -c gtk-redshift -s h --description 'Display help message.'
complete -c gtk-redshift -s v --description 'Enable verbose output.'
complete -c gtk-redshift -s V --description 'Show program version.'
complete -c gtk-redshift -s b --description 'Screen brightness to apply (between 0. 1 and 1. 0).'
complete -c gtk-redshift -s c --description 'Load settings from specified configuration file.'
complete -c gtk-redshift -s g --description 'Additional gamma correction to apply.'
complete -c gtk-redshift -s l --description 'Your current location, in degrees, given as floating point numbers, towards n…'
complete -c gtk-redshift -s m --description 'Method to use to set color temperature (Use "-m list" to see available method…'
complete -c gtk-redshift -s o --description 'One-shot mode (do not continuously adjust color temperature).'
complete -c gtk-redshift -s O --description 'One-shot manual mode (set color temperature).'
complete -c gtk-redshift -s p --description 'Print mode (only print parameters and exit).'
complete -c gtk-redshift -s P --description 'Reset existing gamma ramps before applying new color effect.'
complete -c gtk-redshift -s x --description 'Reset mode (remove adjustment from screen).'
complete -c gtk-redshift -s r --description 'Disable fading between color temperatures.'
complete -c gtk-redshift -s t --description 'Color temperature to set at daytime/night.'

