# mate-screensaver-command
# Autogenerated from man page /usr/share/man/man1/mate-screensaver-command.1.gz
complete -c mate-screensaver-command -l exit --description 'Causes the screensaver to exit gracefully.'
complete -c mate-screensaver-command -s q -l query --description 'Query the state of the screensaver.'
complete -c mate-screensaver-command -s t -l time --description 'Query the length of time the screensaver has been active.'
complete -c mate-screensaver-command -s l -l lock --description 'Tells the running screensaver process to lock the screen immediately.'
complete -c mate-screensaver-command -s u -l unlock --description 'Tells the running screensaver process to unlock the screen immediately.'
complete -c mate-screensaver-command -s c -l cycle --description 'If the screensaver is active then switch to another graphics demo.'
complete -c mate-screensaver-command -s a -l activate --description 'Turn the screensaver on (blank the screen).'
complete -c mate-screensaver-command -s d -l deactivate --description 'If the screensaver is active then deactivate it (un-blank the screen).'
complete -c mate-screensaver-command -s p -l poke --description 'Poke the running screensaver to simulate user activity.'
complete -c mate-screensaver-command -s i -l inhibit --description 'Inhibit the screensaver from activating.'
complete -c mate-screensaver-command -s n -l application-name --description 'The calling application that is inhibiting the screensaver.'
complete -c mate-screensaver-command -s r -l reason --description 'The reason for inhibiting the screensaver.'
complete -c mate-screensaver-command -s V -l version --description 'Version of this application AUTHORS.'

