# mate-seahorse-tool
# Autogenerated from man page /usr/share/man/man1/mate-seahorse-tool.1.gz
complete -c mate-seahorse-tool -s '?' -l help --description 'Show summary of all options and exit.'
complete -c mate-seahorse-tool -l usage --description 'Display brief usage message and exit. \\" End List  .'
complete -c mate-seahorse-tool -s i -l import --description 'Import keys from the FILE.'
complete -c mate-seahorse-tool -s e -l encrypt --description 'Encrypt FILE.'
complete -c mate-seahorse-tool -s s -l sign --description 'Sign FILE with default key.'
complete -c mate-seahorse-tool -s n -l encrypt-sign --description 'Encrypt and sign FILE with default key.'
complete -c mate-seahorse-tool -s d -l decrypt --description 'Decrypt encrypted FILE.'
complete -c mate-seahorse-tool -s v -l verify --description 'Verify signature FILE.'
complete -c mate-seahorse-tool -s T -l uri-list --description 'Read list of URIs on standard in.'
complete -c mate-seahorse-tool -l version --description 'Show version information and exit.'

