# mate-calculator
# Autogenerated from man page /usr/share/man/man1/mate-calculator.1.gz
complete -c mate-calculator -s s -l solve --description 'Solve the equation provided following this option.'
complete -c mate-calculator -l version --description 'Output version information and exit.'
complete -c mate-calculator -s h -s '?' -l help --description 'Print standard command line options.'

