# mate-session-properties
# Autogenerated from man page /usr/share/man/man1/mate-session-properties.1.gz
complete -c mate-session-properties -l display --description 'X display to use.'
complete -c mate-session-properties -l version --description 'Output version information and exit.'
complete -c mate-session-properties -s '?' -s h -l help --description 'Print standard command line options.'

