# mate-calc
# Autogenerated from man page /usr/share/man/man1/mate-calc.1.gz
complete -c mate-calc -s s -l solve --description 'Solve the equation provided following this option.'
complete -c mate-calc -l version --description 'Output version information and exit.'
complete -c mate-calc -s h -s '?' -l help --description 'Print standard command line options.'

