# mate-screensaver
# Autogenerated from man page /usr/share/man/man1/mate-screensaver.1.gz
complete -c mate-screensaver -l display --description 'X display to use.'
complete -c mate-screensaver -l no-daemon --description 'Don\'t start as a daemon.'
complete -c mate-screensaver -l debug --description 'Enable debugging messages for mate-screensaver.'
complete -c mate-screensaver -l version --description 'Output version information and exit.'
complete -c mate-screensaver -s h -l help --description 'Print standard command line options.'

