# mate-volume-control
# Autogenerated from man page /usr/share/man/man1/mate-volume-control.1.gz
complete -c mate-volume-control -s b -l backend --description 'Launch mate-volume-control with the selected sound system backend.'
complete -c mate-volume-control -s d -l debug --description 'Enable debugging code.'
complete -c mate-volume-control -s p -l page --description 'Launch mate-volume-control on the specified page/tab.'
complete -c mate-volume-control -s v -l version --description 'Output version information and exit.'
complete -c mate-volume-control -l display --description 'X display to use.'
complete -c mate-volume-control -s '?' -s h -l help --description 'Print standard command line options.'
complete -c mate-volume-control -l help-all --description 'Print all command line options.'
complete -c mate-volume-control -l help-gtk --description 'Print GTK+ options.'

