# mate-power-manager
# Autogenerated from man page /usr/share/man/man1/mate-power-manager.1.gz
complete -c mate-power-manager -l help --description 'Show summary of options.'
complete -c mate-power-manager -l verbose --description 'Show extra debugging.'
complete -c mate-power-manager -l no-daemon --description 'Do not detach mate-power-manager into the background so that error messages w…'

