# mate-volume-control-status-icon
# Autogenerated from man page /usr/share/man/man1/mate-volume-control-status-icon.1.gz
complete -c mate-volume-control-status-icon -s v -l version --description 'Output version information and exit.'
complete -c mate-volume-control-status-icon -s d -l debug --description 'Enable debugging code.'
complete -c mate-volume-control-status-icon -l display --description 'X display to use.'
complete -c mate-volume-control-status-icon -s '?' -s h -l help --description 'Print standard command line options.'
complete -c mate-volume-control-status-icon -l help-all --description 'Print all command line options.'
complete -c mate-volume-control-status-icon -l help-gtk --description 'Print GTK+ options.'

