# mate-session-save
# Autogenerated from man page /usr/share/man/man1/mate-session-save.1.gz
complete -c mate-session-save -l logout --description 'Log out.'
complete -c mate-session-save -l force-logout --description 'Log out, ignoring any existing inhibitors.'
complete -c mate-session-save -l logout-dialog --description 'Show logout dialog.'
complete -c mate-session-save -l shutdown-dialog --description 'Show shutdown dialog.'
complete -c mate-session-save -l gui --description 'br Use dialog boxes for errors.'
complete -c mate-session-save -l display --description 'X display to use.'
complete -c mate-session-save -l version --description 'Output version information and exit.'
complete -c mate-session-save -s '?' -s h -l help --description 'Print standard command line options.'

