# pluma
# Autogenerated from man page /usr/share/man/man1/pluma.1.gz
complete -c pluma -l display --description 'X display to use.'
complete -c pluma -l encoding --description 'Set the character encoding to be used for opening the files listed on the com…'
complete -c pluma -l new-window --description 'Create a new toplevel window in an existing instance of pluma.'
complete -c pluma -l new-document --description 'Create a new document in an existing instance of pluma, on the last Pluma win…'
complete -c pluma -l list-encodings --description 'Display list of possible values for the encoding option and exit.'
complete -c pluma -l version --description 'Output version information and exit.'
complete -c pluma -s '?' -s h -l help --description 'Print standard command line options.'

