# sassc
# Autogenerated from man page /usr/share/man/man1/sassc.1.gz
complete -c sassc -s s -l stdin --description 'Read input from standard input instead of an input file.'
complete -c sassc -s t -l style --description 'Output style.  Can be: nested, expanded, compact, compressed.'
complete -c sassc -s l -l line-numbers --description 'Emit comments showing original line numbers. HP --line-comments.'
complete -c sassc -s I -l load-path --description 'Set Sass import path.'
complete -c sassc -s P -l plugin-path --description 'Set path to autoload plugins.'
complete -c sassc -s m -l sourcemap --description 'Emit source map (auto or inline).'
complete -c sassc -s M -l omit-map-comment --description 'Omits the source map url comment.'
complete -c sassc -s p -l precision --description 'Set the precision for numbers.'
complete -c sassc -s a -l sass --description 'Treat input as indented syntax.'
complete -c sassc -s v -l version --description 'Display compiled versions.'
complete -c sassc -l line-comments --description '.'
complete -c sassc -s h -l help --description 'Display this help message.'

