# tilda
# Autogenerated from man page /usr/share/man/man1/tilda.1.gz
complete -c tilda -s '?' -l help --description 'Show help options Application Options:.'
complete -c tilda -s b -l background-color --description 'Set the background color.'
complete -c tilda -s c -l command --description 'Run a command at startup.'
complete -c tilda -s h -l hidden --description 'Start Tilda hidden.'
complete -c tilda -s f -l font --description 'Set the font to the following string.'
complete -c tilda -s l -l lines --description 'Scrollback Lines.'
complete -c tilda -s s -l scrollbar --description 'Use Scrollbar.'
complete -c tilda -s v -l version --description 'Print the version, then exit.'
complete -c tilda -s w -l working-dir --description 'Set Initial Working Directory.'
complete -c tilda -s x -l x-pos --description 'X Position.'
complete -c tilda -s y -l y-pos --description 'Y Position.'
complete -c tilda -s t -l background-alpha --description 'Opaqueness: 0-100%.'
complete -c tilda -s C -l config --description 'Show Configuration Wizard.'
complete -c tilda -l display --description 'X display to use COPYRIGHT Copyright © 2012,2020 Sebastian Geiger (lanoxx@gmx.'

