# update-menus
# Autogenerated from man page /usr/share/man/man1/update-menus.1.gz
complete -c update-menus -s v --description 'Verbose output.  Shows all arguments to the /etc/menu-methods programs.'
complete -c update-menus -s d --description 'Debug output.  Generates loads of unintelligible output.'
complete -c update-menus -s h -l help --description 'Display usage help and exit.'
complete -c update-menus -l menufilesdir --description 'Adds directory <dir> to the list of directories to search for menu files in.'
complete -c update-menus -l menumethod --description 'Process only the menu method <method> instead of all the menu methods found.'
complete -c update-menus -l nodefaultdirs --description 'Disables the search of menu entries in system menu directories.'
complete -c update-menus -l nodpkgcheck --description 'Do not discard menu entries for packages that are not installed according to …'
complete -c update-menus -l remove --description 'Remove the menus by calling the menu-methods with --remove.'
complete -c update-menus -l stdout --description 'Output the menu list in a format suitable as input for install-menu or a menu…'
complete -c update-menus -l version --description 'Output version information and exit.'

