# webcamoid
# Autogenerated from man page /usr/share/man/man1/webcamoid.1.gz
complete -c webcamoid -s h -l help --description 'Displays this help.'
complete -c webcamoid -s v -l version --description 'Displays version information.'
complete -c webcamoid -o 'c<PATH>' -l 'config<PATH>' --description 'Load settings from PATH.'
complete -c webcamoid -o 'q<PATH1;PATH2;PATH3;...>' -l 'qmlpaths<PATH1;PATH2;PATH3;...>' --description 'Semi-colon separated list of paths to search the Qml interface.'
complete -c webcamoid -s r -l recursive --description 'Search in the specified plugins paths recursively.'
complete -c webcamoid -o 'p<PATH1;PATH2;PATH3;...>' -l 'paths<PATH1;PATH2;PATH3;...>' --description 'Semi-colon separated list of paths to search for plugins.'
complete -c webcamoid -o 'b<PATH1;PATH2;PATH3;...>' -l 'no-load<PATH1;PATH2;PATH3;...>' --description 'Semi-colon separated list of paths to avoid loading.'
complete -c webcamoid -s c -l config --description 'Load settings from PATH.'
complete -c webcamoid -s q -l qmlpaths --description 'Semi-colon separated list of paths to search the Qml interface.'
complete -c webcamoid -s p -l paths --description 'Semi-colon separated list of paths to search for plugins.'
complete -c webcamoid -s b -l no-load --description 'Semi-colon separated list of paths to avoid loading.'
complete -c webcamoid -l vcam --description 'Semi-colon separated list of paths to search for virtual camera driver.'

