# x-session-manager
# Autogenerated from man page /usr/share/man/man1/x-session-manager.1.gz
complete -c x-session-manager -s a -l autostart --description 'Start all applications defined in "DIR", instead of starting the applications…'
complete -c x-session-manager -s f -l failsafe --description 'Run in fail-safe mode.  User-specified applications will not be started.'
complete -c x-session-manager -l debug --description 'Enable debugging code.'
complete -c x-session-manager -l display --description 'X display to use.'
complete -c x-session-manager -l version --description 'Output version information and exit.'
complete -c x-session-manager -s '?' -s h -l help --description 'Print standard command line options.'

