# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
complete -c x-window-manager -s d -l display --description 'X display to use.'
complete -c x-window-manager -l sync --description 'br Make X calls synchronous.'
complete -c x-window-manager -l replace --description 'Replace the currently running window manager with Marco.'
complete -c x-window-manager -l sm-disable --description 'Disable the connection to the session manager.'
complete -c x-window-manager -l sm-client-id --description 'Specify a session management ID.'
complete -c x-window-manager -l sm-save-file --description 'Restore from a session management savefile.'
complete -c x-window-manager -s c -l composite --description 'Turn compositing ON.'
complete -c x-window-manager -l no-composite --description 'Turn compositing OFF.'
complete -c x-window-manager -l no-force-fullscreen --description 'Do not create fullscreen windows without decorations.'
complete -c x-window-manager -l version --description 'Print current version information and exit.'

